[pytest]
testpaths = tests
addopts = --basetemp=C:/tmp/probabilistic-automata-time-series-pytest -p no:cacheprovider
norecursedirs =
    .git
    .pytest_cache
    pytest-cache-files-*
    results
    data
